spring:
  application:
    name: hefsharding
  sharding:
    datasources:
      ds0:
        username: orm_user
        password: orm2024ps
        url: jdbc:mysql://localhost:3306/orm_test01?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
      ds1:
        username: orm_user
        password: orm2024ps
        url: jdbc:mysql://localhost:3306/orm_test02?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
mybatis:
  mapper-locations: classpath:mapper/**/*.xml