spring:
  application:
    name: hefsharding
  datasource:
    username: orm_user
    password: orm2024ps
    url: jdbc:mysql://localhost:3306/orm_test?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
mybatis:
  mapper-locations: classpath:mapper/**/*.xml