spring:
  application:
    name: hefsharding
  sharding:
    datasources:
      ds0:
        username: orm_user
        password: orm2024ps
        url: jdbc:mysql://localhost:3306/orm_test01?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
      ds1:
        username: orm_user
        password: orm2024ps
        url: jdbc:mysql://localhost:3306/orm_test02?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
    tables:
      user:
        # 实际的表
        actualDataNodes: ds0.user0,ds0.user1,ds0.user2,ds1.user0,ds1.user1,ds1.user2
        # 分库策略
        databaseStrategy:
          shardingColumn: id
          algorithmExpression: ds$->{id % 2}
        # 分表策略
        tableStrategy:
          shardingColumn: id
          algorithmExpression: user$->{id % 3}
      order:
        # 实际的表
        actualDataNodes: ds0.order0,ds0.order1,ds1.order0,ds1.order1
        # 分库策略
        databaseStrategy:
          shardingColumn: uid
          algorithmExpression: ds$->{uid % 2}
        # 分表策略
        tableStrategy:
          shardingColumn: id
          algorithmExpression: order$->{id % 2}
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
logging:
  level:
    root: error
    io.github.hefrankeleyn.hefsharding: debug